"""Shared interfaces for periodic lattice geometry."""

from __future__ import annotations

from abc import ABC, abstractmethod
from typing import TypeAlias, Self

import numpy as np
from numpy.typing import NDArray


FloatArray: TypeAlias = NDArray[np.float64]
IntArray: TypeAlias = NDArray[np.int64]


class Lattice(ABC):
    r"""
    Abstract discrete translation lattice.

    A lattice in ``d`` dimensions is generated from a primitive-basis matrix
    ``A`` according to

    .. math::

        \mathbf R_{\mathbf n}=A\mathbf n,

    where ``n`` is an integer mode vector.
    """

    @property
    @abstractmethod
    def dimension(self) -> int:
        """Return the spatial dimension."""
        raise NotImplementedError

    @property
    @abstractmethod
    def measure(self) -> float:
        """
        Return the primitive-cell length, area, or volume.

        Returns
        -------
        float
            Primitive-cell measure appropriate to the lattice dimension.
        """
        raise NotImplementedError


    @abstractmethod
    def vector(self, indices: IntArray) -> FloatArray:
        """Construct a lattice vector from integer mode coefficients."""
        raise NotImplementedError


class DirectLattice(Lattice):
    """
    Abstract direct Bravais lattice.

    A direct lattice defines the discrete real-space translations that leave
    a periodic system invariant.
    """

class ReciprocalLattice(Lattice):
    """
    Abstract reciprocal Bravais lattice.

    A reciprocal lattice is generated by a primitive reciprocal basis

    .. math::

        B
        =
        \\begin{bmatrix}
        \\mathbf b_1
        &
        \\cdots
        &
        \\mathbf b_d
        \\end{bmatrix}.

    Its lattice vectors are

    .. math::

        \\mathbf G_{\\mathbf m}
        =
        B\\mathbf m,

    where

    .. math::

        \\mathbf m
        \\in
        \\mathbb Z^d.

    A reciprocal lattice may be constructed directly from its primitive
    reciprocal vectors or derived from a direct lattice. If ``A`` is the
    direct-lattice primitive basis, the reciprocal primitive basis is

    .. math::

        B
        =
        2\\pi A^{-\\mathsf T}.

    Equivalently,

    .. math::

        A^{\\mathsf T}B
        =
        2\\pi I.

    Notes
    -----
    The reciprocal-lattice object represents the reciprocal lattice itself.
    It does not need to retain the direct lattice from which it may have been
    constructed.

    Concrete dimensional subclasses define their own primary constructors:

    - ``ReciprocalLattice1D(b1)``
    - ``ReciprocalLattice2D(b1, b2)``
    - ``ReciprocalLattice3D(b1, b2, b3)``

    Each subclass must also implement ``from_direct_lattice`` as an alternate
    constructor.
    """

    @classmethod
    @abstractmethod
    def from_direct_lattice(
        cls,
        direct_lattice: DirectLattice,
    ) -> Self:
        """
        Construct a reciprocal lattice from a direct lattice.

        For a direct primitive-basis matrix ``A``, the reciprocal primitive
        basis is

        .. math::

            B
            =
            2\\pi A^{-\\mathsf T}.

        Parameters
        ----------
        direct_lattice:
            Direct lattice whose primitive basis determines the reciprocal
            primitive basis.

        Returns
        -------
        Self
            Reciprocal lattice of the same spatial dimension as
            ``direct_lattice``.

        Raises
        ------
        TypeError
            If the direct lattice has the wrong concrete dimension for the
            reciprocal-lattice subclass.

        Notes
        -----
        This is a class method because it is an alternate constructor.
        Concrete implementations should return ``cls(...)`` rather than
        naming the subclass explicitly.
        """
        raise NotImplementedError

class WignerSeitzCell(ABC):
    """
    Abstract Wigner--Seitz cell of a lattice.

    The Wigner--Seitz cell contains points at least as close to the origin as
    to every other point of the source lattice.
    """

    @property
    @abstractmethod
    def lattice(self) -> Lattice:
        """Return the lattice whose Wigner--Seitz cell is represented."""
        raise NotImplementedError

    @property
    @abstractmethod
    def measure(self) -> float:
        """Return the cell length, area, or volume."""
        raise NotImplementedError

    @abstractmethod
    def contains(self, point: FloatArray) -> bool:
        """Return whether a point lies inside the closed cell."""
        raise NotImplementedError



class FirstBrillouinZone(WignerSeitzCell):
    """
    Abstract first Brillouin zone.

    The first Brillouin zone is the Wigner--Seitz cell of a reciprocal
    lattice.
    """

    @property
    @abstractmethod
    def reciprocal_lattice(self) -> ReciprocalLattice:
        """Return the reciprocal lattice that generates the zone."""
        raise NotImplementedError

    @abstractmethod
    def reduce(self, wavevector: FloatArray) -> FloatArray:
        """Reduce a wavevector to one representative inside the zone."""
        raise NotImplementedError

