# src/physkit/periodic/lattice/lattice1d.py

from __future__ import annotations

import numpy as np

from physkit.periodic.lattice.base import (
    FloatArray,
    IntArray,
)

from physkit.periodic.lattice.base import (
    DirectLattice,
    ReciprocalLattice,
    WignerSeitzCell,
    FirstBrillouinZone,
)

class DirectLattice1D(DirectLattice):
    """
    One-dimensional direct Bravais lattice.

    The lattice is generated by the primitive basis

    .. math::

        A
        =
        \\begin{bmatrix}
        a_1
        \\end{bmatrix},

    where ``a_1`` is represented by the positive scalar lattice constant
    ``a``.

    Every direct-lattice translation is

    .. math::

        R_n
        =
        na,

    where

    .. math::

        n
        \\in
        \\mathbb Z.

    Parameters
    ----------
    lattice_constant:
        Positive primitive lattice constant ``a``.

    Attributes
    ----------
    lattice_constant:
        Primitive direct-lattice basis vector represented as a scalar.
    """

    def __init__(
        self,
        lattice_constant: float,
    ) -> None:
        # In one dimension, the primitive direct basis contains one vector.
        # The vector is represented by its scalar Cartesian component.
        self.lattice_constant: float = float(
            lattice_constant
        )

        self.check_args()

        # The common lattice interface represents a primitive basis as a
        # matrix whose columns are primitive vectors. In one dimension, this
        # produces a matrix with shape (1, 1).
        self._primitive_basis: FloatArray = np.array(
            [[self.lattice_constant]],
            dtype=np.float64,
        )

        # The basis defines the lattice and must remain fixed after
        # construction.
        self._primitive_basis.setflags(
            write=False
        )

    def check_args(self) -> None:
        """
        Validate the direct-lattice arguments.

        Returns
        -------
        None

        Raises
        ------
        ValueError
            If ``lattice_constant`` is nonfinite or nonpositive.
        """
        if not np.isfinite(
            self.lattice_constant
        ):
            raise ValueError(
                "lattice_constant must be finite."
            )

        if self.lattice_constant <= 0.0:
            raise ValueError(
                "lattice_constant must be positive."
            )

    @property
    def dimension(self) -> int:
        """
        Return the spatial dimension.

        Returns
        -------
        int
            Spatial dimension, equal to one.
        """
        return 1

    @property
    def primitive_basis(self) -> FloatArray:
        """
        Return the direct primitive-basis matrix.

        Returns
        -------
        FloatArray
            Read-only matrix ``[[a]]`` with shape ``(1, 1)``.
        """
        return self._primitive_basis

    @property
    def measure(self) -> float:
        """
        Return the measure associated with the primitive basis.

        The measure is

        .. math::

            |\\det A|.

        Returns
        -------
        float
            Length, area, or volume associated with the primitive basis in
            one, two, or three dimensions, respectively.

        Notes
        -----
        A lattice is a discrete point set and therefore has zero Lebesgue
        measure. This property represents the measure of a fundamental domain
        of the lattice, equivalently the lattice covolume.
        """
        return float(
            abs(
                np.linalg.det(
                    self.primitive_basis
                )
            )
        )

    @property
    def a1(self) -> float:
        """
        Return the primitive direct-lattice basis vector.

        Returns
        -------
        float
            Scalar primitive basis vector ``a_1 = a``.
        """
        return self.lattice_constant

    def vector(
        self,
        modes: IntArray,
    ) -> FloatArray:
        """
        Construct direct-lattice vectors.

        The lattice vectors are

        .. math::

            R_n
            =
            na.

        Parameters
        ----------
        modes:
            Integer lattice modes. The input may be a scalar or an array.

        Returns
        -------
        FloatArray
            Direct-lattice vectors with the same shape as ``modes``.
        """
        mode_array: IntArray = np.asarray(
            modes,
            dtype=np.int64,
        )

        return np.asarray(
            mode_array
            * self.lattice_constant,
            dtype=np.float64,
        )

    def translation(
        self,
        cell_index: int,
    ) -> float:
        """
        Construct one direct-lattice translation.

        Parameters
        ----------
        cell_index:
            Integer lattice mode ``n``.

        Returns
        -------
        float
            Direct-lattice translation ``R_n = na``.

        Raises
        ------
        TypeError
            If ``cell_index`` is not an integer.
        """
        if not isinstance(
            cell_index,
            (int, np.integer),
        ):
            raise TypeError(
                "cell_index must be an integer."
            )

        return (
            float(cell_index)
            * self.lattice_constant
        )


class ReciprocalLattice1D(ReciprocalLattice):
    """
    One-dimensional reciprocal Bravais lattice.

    The reciprocal lattice is generated by the primitive reciprocal basis

    .. math::

        B
        =
        \\begin{bmatrix}
        b_1
        \\end{bmatrix}.

    Every reciprocal-lattice vector is

    .. math::

        G_m
        =
        mb_1,

    where

    .. math::

        m
        \\in
        \\mathbb Z.

    Parameters
    ----------
    b1:
        Nonzero primitive reciprocal-lattice basis vector represented as a
        scalar.

    Attributes
    ----------
    b1:
        Primitive reciprocal-lattice basis vector.

    Notes
    -----
    Use ``from_direct_lattice`` to derive ``b1`` from a direct lattice:

    .. math::

        b_1
        =
        \\frac{2\\pi}{a_1}.
    """

    def __init__(
        self,
        b1: float,
    ) -> None:
        # A reciprocal lattice is defined by its own primitive basis. It does
        # not need to retain the direct lattice from which it may have been
        # derived.
        self.b1: float = float(b1)

        self.check_args()

        self._primitive_basis: FloatArray = np.array(
            [[self.b1]],
            dtype=np.float64,
        )

        self._primitive_basis.setflags(
            write=False
        )

    @classmethod
    def from_direct_lattice(
        cls,
        direct_lattice: DirectLattice1D,
    ) -> ReciprocalLattice1D:
        """
        Construct a reciprocal lattice from a direct lattice.

        The direct and reciprocal primitive bases satisfy

        .. math::

            A^{\\mathsf T}B
            =
            2\\pi I.

        Therefore, in one dimension,

        .. math::

            b_1
            =
            \\frac{2\\pi}{a_1}.

        Parameters
        ----------
        direct_lattice:
            One-dimensional direct lattice.

        Returns
        -------
        ReciprocalLattice1D
            Reciprocal lattice derived from ``direct_lattice``.

        Raises
        ------
        TypeError
            If ``direct_lattice`` is not a ``DirectLattice1D`` instance.
        """
        if not isinstance(
            direct_lattice,
            DirectLattice1D,
        ):
            raise TypeError(
                "direct_lattice must be a "
                "DirectLattice1D instance."
            )

        reciprocal_basis: FloatArray = (
            2.0
            * np.pi
            * np.linalg.inv(
                direct_lattice.primitive_basis
            ).T
        )

        return cls(
            b1=float(
                reciprocal_basis[0, 0]
            )
        )

    def check_args(self) -> None:
        """
        Validate the reciprocal-lattice arguments.

        Returns
        -------
        None

        Raises
        ------
        ValueError
            If ``b1`` is nonfinite or zero.
        """
        if not np.isfinite(self.b1):
            raise ValueError(
                "b1 must be finite."
            )

        if np.isclose(self.b1, 0.0):
            raise ValueError(
                "b1 must be nonzero."
            )

    @property
    def dimension(self) -> int:
        """
        Return the spatial dimension.

        Returns
        -------
        int
            Spatial dimension, equal to one.
        """
        return 1

    @property
    def primitive_basis(self) -> FloatArray:
        """
        Return the reciprocal primitive-basis matrix.

        Returns
        -------
        FloatArray
            Read-only matrix ``[[b1]]`` with shape ``(1, 1)``.
        """
        return self._primitive_basis

    def vector(
        self,
        modes: IntArray,
    ) -> FloatArray:
        """
        Construct reciprocal-lattice vectors.

        The reciprocal vectors are

        .. math::

            G_m
            =
            mb_1.

        Parameters
        ----------
        modes:
            Integer reciprocal-lattice modes. The input may be a scalar or
            an array.

        Returns
        -------
        FloatArray
            Reciprocal-lattice vectors with the same shape as ``modes``.
        """
        mode_array: IntArray = np.asarray(
            modes,
            dtype=np.int64,
        )

        return np.asarray(
            mode_array
            * self.b1,
            dtype=np.float64,
        )


class WignerSeitzCell1D(WignerSeitzCell):
    """
    Wigner--Seitz cell of a one-dimensional direct lattice.

    For a direct lattice generated by ``a``, the Wigner--Seitz cell centered
    at the origin is

    .. math::

        \\mathcal W
        =
        \\left[
        -\\frac{a}{2},
        +\\frac{a}{2}
        \\right].

    Parameters
    ----------
    lattice:
        Direct lattice whose Wigner--Seitz cell is constructed.

    Attributes
    ----------
    lower:
        Lower cell boundary ``-a/2``.
    upper:
        Upper cell boundary ``+a/2``.
    """

    def __init__(
        self,
        lattice: DirectLattice1D,
    ) -> None:
        self._lattice = lattice

        self.check_args()

        self.lower: float = (
            -0.5
            * self._lattice.lattice_constant
        )

        self.upper: float = (
            +0.5
            * self._lattice.lattice_constant
        )

    def check_args(self) -> None:
        """
        Validate the source lattice.

        Returns
        -------
        None

        Raises
        ------
        TypeError
            If ``lattice`` is not a ``DirectLattice1D`` instance.
        """
        if not isinstance(
            self._lattice,
            DirectLattice1D,
        ):
            raise TypeError(
                "lattice must be a "
                "DirectLattice1D instance."
            )

    @property
    def lattice(self) -> DirectLattice1D:
        """
        Return the source direct lattice.

        Returns
        -------
        DirectLattice1D
            Direct lattice that generates this cell.
        """
        return self._lattice

    @property
    def measure(self) -> float:
        """
        Return the Wigner--Seitz-cell measure.

        Returns
        -------
        float
            Cell length ``a``.
        """
        return self.upper - self.lower

    def contains(
        self,
        point: FloatArray,
    ) -> bool:
        """
        Determine whether a point lies inside the cell.

        Parameters
        ----------
        point:
            Scalar or one-element coordinate array.

        Returns
        -------
        bool
            ``True`` when the point lies in the closed interval
            ``[lower, upper]``.

        Raises
        ------
        ValueError
            If the input does not contain exactly one coordinate.
        """
        point_array = np.asarray(
            point,
            dtype=np.float64,
        )

        if point_array.size != 1:
            raise ValueError(
                "point must contain exactly one coordinate."
            )

        coordinate = float(
            point_array.reshape(-1)[0]
        )

        return bool(
            self.lower
            <= coordinate
            <= self.upper
        )


class FirstBrillouinZone1D(FirstBrillouinZone):
    """
    First Brillouin zone of a one-dimensional reciprocal lattice.

    The first Brillouin zone is the Wigner--Seitz cell of the reciprocal
    lattice:

    .. math::

        \\mathcal B_1
        =
        \\left[
        -\\frac{|b_1|}{2},
        +\\frac{|b_1|}{2}
        \\right].

    Parameters
    ----------
    reciprocal_lattice:
        Reciprocal lattice whose first Brillouin zone is constructed.

    Attributes
    ----------
    lower:
        Lower zone boundary ``-|b1|/2``.
    upper:
        Upper zone boundary ``+|b1|/2``.
    """

    def __init__(
        self,
        reciprocal_lattice: ReciprocalLattice1D,
    ) -> None:
        self._reciprocal_lattice = (
            reciprocal_lattice
        )

        self.check_args()

        # The orientation of b1 does not change the geometric zone. Its width
        # is determined by the distance between neighboring reciprocal points.
        reciprocal_spacing = abs(
            self._reciprocal_lattice.b1
        )

        self.lower: float = (
            -0.5
            * reciprocal_spacing
        )

        self.upper: float = (
            +0.5
            * reciprocal_spacing
        )

    def check_args(self) -> None:
        """
        Validate the reciprocal lattice.

        Returns
        -------
        None

        Raises
        ------
        TypeError
            If ``reciprocal_lattice`` is not a
            ``ReciprocalLattice1D`` instance.
        """
        if not isinstance(
            self._reciprocal_lattice,
            ReciprocalLattice1D,
        ):
            raise TypeError(
                "reciprocal_lattice must be a "
                "ReciprocalLattice1D instance."
            )

    @property
    def reciprocal_lattice(
        self,
    ) -> ReciprocalLattice1D:
        """
        Return the reciprocal lattice.

        Returns
        -------
        ReciprocalLattice1D
            Reciprocal lattice that generates the zone.
        """
        return self._reciprocal_lattice

    @property
    def lattice(
        self,
    ) -> ReciprocalLattice1D:
        """
        Return the source lattice of the Wigner--Seitz construction.

        Returns
        -------
        ReciprocalLattice1D
            Reciprocal lattice viewed as the source lattice.
        """
        return self._reciprocal_lattice

    @property
    def measure(self) -> float:
        """
        Return the first-Brillouin-zone measure.

        Returns
        -------
        float
            Zone length ``|b1|``.
        """
        return self.upper - self.lower

    def contains(
        self,
        point: FloatArray,
    ) -> bool:
        """
        Determine whether a wavevector lies inside the zone.

        Parameters
        ----------
        point:
            Scalar or one-element wavevector array.

        Returns
        -------
        bool
            ``True`` when the point lies inside the closed first Brillouin
            zone.

        Raises
        ------
        ValueError
            If the input does not contain exactly one wavevector.
        """
        point_array = np.asarray(
            point,
            dtype=np.float64,
        )

        if point_array.size != 1:
            raise ValueError(
                "point must contain exactly one wavevector."
            )

        wavevector = float(
            point_array.reshape(-1)[0]
        )

        return bool(
            self.lower
            <= wavevector
            <= self.upper
        )

    def reduce(
        self,
        wavevector: FloatArray,
    ) -> FloatArray:
        """
        Reduce wavevectors into the first Brillouin zone.

        The reduction maps each wavevector into the half-open interval

        .. math::

            \\left[
            -\\frac{|b_1|}{2},
            +\\frac{|b_1|}{2}
            \\right).

        Parameters
        ----------
        wavevector:
            Scalar or array of wavevectors.

        Returns
        -------
        FloatArray
            Equivalent wavevectors in the first Brillouin zone.
        """
        wavevector_array: FloatArray = np.asarray(
            wavevector,
            dtype=np.float64,
        )

        return np.asarray(
            (
                wavevector_array
                - self.lower
            )
            % self.measure
            + self.lower,
            dtype=np.float64,
        )
