# src/physkit/periodic/lattice/lattice2d.py

from __future__ import annotations

import numpy as np
from scipy.spatial import ConvexHull
from scipy.spatial import HalfspaceIntersection

from physkit.periodic.lattice.base import (
    FloatArray,
    IntArray,
)

from physkit.periodic.lattice.base import (
    DirectLattice,
    ReciprocalLattice,
    WignerSeitzCell,
    FirstBrillouinZone,
)


class DirectLattice2D(DirectLattice):
    r"""
    Two-dimensional direct Bravais lattice.

    The lattice is generated by two primitive direct-lattice vectors,

    .. math::

        \mathbf a_1,
        \qquad
        \mathbf a_2.

    These vectors form the primitive-basis matrix

    .. math::

        A
        =
        \begin{bmatrix}
        \mathbf a_1
        &
        \mathbf a_2
        \end{bmatrix}.

    Every direct-lattice vector is

    .. math::

        \mathbf R_{\mathbf n}
        =
        A\mathbf n
        =
        n_1\mathbf a_1
        +
        n_2\mathbf a_2,

    where

    .. math::

        \mathbf n
        =
        \begin{bmatrix}
        n_1\\
        n_2
        \end{bmatrix}
        \in
        \mathbb Z^2.

    Parameters
    ----------
    a1:
        First primitive direct-lattice vector with shape ``(2,)``.
    a2:
        Second primitive direct-lattice vector with shape ``(2,)``.

    Attributes
    ----------
    a1:
        Read-only first primitive direct-lattice vector.
    a2:
        Read-only second primitive direct-lattice vector.
    """
    dimension=2

    def __init__(
        self,
        a1: FloatArray,
        a2: FloatArray,
    ) -> None:
        # Copy the primitive vectors so making the internal arrays read-only
        # does not change arrays owned by the caller.
        a1_array: FloatArray = np.array(a1, dtype=np.float64, copy=True)
        a2_array: FloatArray = np.array(a2, dtype=np.float64, copy=True)

        self.check_primitive_vector(a1_array)
        self.check_primitive_vector(a2_array)
        self.check_primitive_vectors_linearly_independent(a1_array, a2_array)

        # Primitive vectors are stored as columns:
        #
        #     A = [a1 a2].
        self.A: FloatArray = (
            np.column_stack((a1_array, a2_array))
        )

    @property
    def a1(self) -> FloatArray:
        """
        Return the first direct primitive vector.

        Returns
        -------
        FloatArray
            Mutable view of the first column of ``A``.
        """
        return self.A[:,0]

    @property
    def a2(self) -> FloatArray:
        """
        Return the second direct primitive vector.

        Returns
        -------
        FloatArray
            Mutable view of the second column of ``A``.
        """
        return self.A[:,1]

    def check_primitive_vector(self, vector: FloatArray):
        """
        Validate one two-dimensional primitive vector.

        Parameters
        ----------
        vector:
            Primitive vector to validate.

        Raises
        ------
        ValueError
            If ``vector`` does not have shape ``(2,)`` or contains
            non-finite values.
        """

        if vector.shape != (2,):
            raise ValueError("a1 must have shape (2,).")
        if not np.all(np.isfinite(vector)):
            raise ValueError(
                "primitive vectors must contain only finite values."
            )

    def check_primitive_vectors_linearly_independent(self,
            a1: FloatArray,
            a2: FloatArray
        ) -> None:
        """
        Validate that the primitive vectors are linearly independent.

        Parameters
        ----------
        a1:
            First primitive vector.
        a2:
            Second primitive vector.

        Raises
        ------
        ValueError
            If the primitive vectors are linearly dependent.
        """
        A = np.column_stack((a1, a2))

        if np.isclose(np.linalg.det(A), 0.0):
            raise ValueError(
                "a1 and a2 must be linearly independent."
            )

    @property
    def measure(self) -> float:
        """
        Return the fundamental-region area.

        Returns
        -------
        float
            Area :math:`|\\det A|`.
        """
        return float(abs(np.linalg.det(self.A)))

    def vector(
        self,
        indices: IntArray,
    ) -> FloatArray:
        """
        Construct direct-lattice vectors.

        The lattice vectors are

        .. math::

            \\mathbf{R}_{\\mathbf n}
            =
            n_1\\mathbf{a}_1
            +
            n_2\\mathbf{a}_2.

        Parameters
        ----------
        indices:
            Integer direct-lattice indices with shape ``(2,)`` or
            ``(..., 2)``.

        Returns
        -------
        FloatArray
            Direct-lattice vectors with the same leading shape as
            ``indices``.

        Raises
        ------
        ValueError
            If the final dimension of ``indices`` is not two.
        """
        index_array: IntArray = np.asarray(
            indices,
            dtype=np.int64,
        )

        if (
            index_array.ndim == 0
            or index_array.shape[-1] != 2
        ):
            raise ValueError(
                "indices must have final dimension 2."
            )

        return np.asarray(
            index_array @ self.A.T,
            dtype=np.float64,
        )


class ReciprocalLattice2D(ReciprocalLattice):
    r"""
    Two-dimensional reciprocal Bravais lattice.

    The reciprocal lattice is generated by two primitive reciprocal vectors,

    .. math::

        \mathbf b_1,
        \qquad
        \mathbf b_2.

    These vectors form the reciprocal primitive-basis matrix

    .. math::

        B
        =
        \begin{bmatrix}
        \mathbf b_1
        &
        \mathbf b_2
        \end{bmatrix}.

    Every reciprocal-lattice vector is

    .. math::

        \mathbf G_{\mathbf m}
        =
        B\mathbf m
        =
        m_1\mathbf b_1
        +
        m_2\mathbf b_2,

    where

    .. math::

        \mathbf m
        =
        \begin{bmatrix}
        m_1\\
        m_2
        \end{bmatrix}
        \in
        \mathbb Z^2.

    Parameters
    ----------
    b1:
        First primitive reciprocal-lattice vector with shape ``(2,)``.
    b2:
        Second primitive reciprocal-lattice vector with shape ``(2,)``.

    Attributes
    ----------
    b1:
        Read-only first primitive reciprocal-lattice vector.
    b2:
        Read-only second primitive reciprocal-lattice vector.
    """
    dimension = 2

    def __init__(
        self,
        b1: FloatArray,
        b2: FloatArray,
    ) -> None:
        # A reciprocal lattice is defined by its own primitive basis. It does
        # not need to retain the direct lattice from which it may have been
        # derived.
        b1_array: FloatArray = np.array(b1, dtype=np.float64, copy=True)
        b2_array: FloatArray = np.array(b2, dtype=np.float64, copy=True)

        self.check_primitive_vector(b1_array)
        self.check_primitive_vector(b1_array)
        self.check_primitive_vectors_linearly_independent(b1_array, b2_array)
        # Reciprocal primitive vectors are stored as columns:
        #     B = [b1 b2].
        self.B: FloatArray = (
            np.column_stack((b1_array, b2_array))
        )

    @property
    def b1(self) -> FloatArray:
        return self.B[:,0]

    @property
    def b2(self) -> FloatArray:
        return self.B[:,1]

    def check_primitive_vector(self, vector: FloatArray):
        """
        Validate one two-dimensional primitive vector.

        Parameters
        ----------
        vector:
            Primitive vector to validate.

        Raises
        ------
        ValueError
            If ``vector`` does not have shape ``(2,)`` or contains
            non-finite values.
        """

        if vector.shape != (2,):
            raise ValueError("a1 must have shape (2,).")
        if not np.all(np.isfinite(vector)):
            raise ValueError(
                "primitive vectors must contain only finite values."
            )

    def check_primitive_vectors_linearly_independent(
            b1: FloatArray,
            b2: FloatArray
        ) -> None:
        """
        Validate that the primitive vectors are linearly independent.

        Parameters
        ----------
        b1:
            First primitive vector.
        b2:
            Second primitive vector.

        Raises
        ------
        ValueError
            If the primitive vectors are linearly dependent.
        """
        B = np.column_stack((b1, b2))

        if np.isclose(np.linalg.det(B), 0.0):
            raise ValueError(
                "a1 and a2 must be linearly independent."
            )


    @classmethod
    def from_direct_lattice(
        cls,
        direct_lattice: DirectLattice2D,
    ) -> ReciprocalLattice2D:
        r"""
        Construct a reciprocal lattice from a direct lattice.

        If ``A`` is the direct primitive-basis matrix, the reciprocal
        primitive-basis matrix is

        .. math::

            B
            =
            2\pi A^{-\mathsf T}.

        The two bases satisfy

        .. math::

            A^{\mathsf T}B
            =
            2\pi I.

        Parameters
        ----------
        direct_lattice:
            Two-dimensional direct lattice.

        Returns
        -------
        ReciprocalLattice2D
            Reciprocal lattice derived from ``direct_lattice``.

        Raises
        ------
        TypeError
            If ``direct_lattice`` is not a ``DirectLattice2D`` instance.
        """
        if not isinstance(direct_lattice, DirectLattice2D):
            raise TypeError(
                "direct_lattice must be a DirectLattice2D instance."
            )

        B: FloatArray = (2.0* np.pi*np.linalg.inv(direct_lattice.A).T)

        return cls(
            b1=B[:, 0],
            b2=B[:, 1],
        )


    @property
    def primitive_basis(self) -> FloatArray:
        """
        Return the reciprocal primitive-basis matrix.

        Returns
        -------
        FloatArray
            Read-only matrix with ``b1`` and ``b2`` as columns. Its shape is
            ``(2, 2)``.
        """
        return self._primitive_basis

    def vector(
        self,
        indices: IntArray,
    ) -> FloatArray:
        """
        Construct reciprocal-lattice vectors.

        The reciprocal vectors are

        .. math::

            \\mathbf{G}_{\\mathbf{m}}
            =
            m_1\\mathbf{b}_1
            +
            m_2\\mathbf{b}_2.

        Parameters
        ----------
        indices:
            Integer reciprocal-lattice indices with shape ``(2,)`` or
            ``(..., 2)``.

        Returns
        -------
        FloatArray
            Reciprocal-lattice vectors with the same leading shape as
            ``indices``.

        Raises
        ------
        ValueError
            If the final dimension of ``indices`` is not two.
        """
        index_array: IntArray = np.asarray(
            indices,
            dtype=np.int64,
        )

        if (
            index_array.ndim == 0
            or index_array.shape[-1] != 2
        ):
            raise ValueError(
                "indices must have final dimension 2."
            )

        return np.asarray(
            index_array
            @ self.primitive_basis.T,
            dtype=np.float64,
        )


class WignerSeitzCell2D(WignerSeitzCell):
    r"""
    Wigner--Seitz cell of a two-dimensional direct lattice.

    Every nonzero direct-lattice vector ``R`` defines a half-plane:

    .. math::

        \mathbf R\cdot\mathbf x
        \leq
        \frac{|\mathbf R|^2}{2}.

    The intersection of these half-planes is the Wigner--Seitz cell centered
    at the origin.

    Parameters
    ----------
    lattice:
        Direct lattice whose Wigner--Seitz cell is constructed.
    neighbor_shell:
        Number of positive and negative lattice-index shells used to construct
        the half-plane intersection.

    Attributes
    ----------
    neighbor_shell:
        Number of neighboring lattice-index shells.
    halfspaces:
        Half-plane inequalities used to construct the cell.
    vertices:
        Counterclockwise polygon vertices.
    """

    def __init__(
        self,
        lattice: DirectLattice2D,
        *,
        neighbor_shell: int = 2,
    ) -> None:
        self._lattice = lattice
        self.neighbor_shell = neighbor_shell

        self.check_args()

        self.halfspaces: FloatArray = (
            self.construct_halfspaces()
        )

        self.vertices: FloatArray = (
            self.construct_vertices()
        )

        self._convex_hull = ConvexHull(
            self.vertices
        )

        self.halfspaces.setflags(write=False)
        self.vertices.setflags(write=False)

    def check_args(self) -> None:
        """
        Validate the Wigner--Seitz-cell arguments.

        Returns
        -------
        None

        Raises
        ------
        TypeError
            If ``lattice`` is not a ``DirectLattice2D`` instance or
            ``neighbor_shell`` is not an integer.
        ValueError
            If ``neighbor_shell`` is less than one.
        """
        if not isinstance(
            self._lattice,
            DirectLattice2D,
        ):
            raise TypeError(
                "lattice must be a "
                "DirectLattice2D instance."
            )

        if not isinstance(
            self.neighbor_shell,
            (int, np.integer),
        ):
            raise TypeError(
                "neighbor_shell must be an integer."
            )

        if self.neighbor_shell < 1:
            raise ValueError(
                "neighbor_shell must be at least 1."
            )

    @property
    def lattice(self) -> DirectLattice2D:
        """
        Return the source direct lattice.

        Returns
        -------
        DirectLattice2D
            Direct lattice that generates the Wigner--Seitz cell.
        """
        return self._lattice

    @property
    def measure(self) -> float:
        """
        Return the Wigner--Seitz-cell area.

        Returns
        -------
        float
            Area enclosed by the Wigner--Seitz polygon.
        """
        return float(
            self._convex_hull.volume
        )

    def construct_indices(self) -> IntArray:
        """
        Construct neighboring direct-lattice indices.

        Returns
        -------
        IntArray
            Nonzero integer index pairs with shape
            ``(number_of_indices, 2)``.
        """
        lower = -self.neighbor_shell
        upper = +self.neighbor_shell

        n1_indices = np.arange(
            lower,
            upper + 1,
            dtype=np.int64,
        )

        n2_indices = np.arange(
            lower,
            upper + 1,
            dtype=np.int64,
        )

        n1_grid, n2_grid = np.meshgrid(
            n1_indices,
            n2_indices,
            indexing="ij",
        )

        lattice_indices: IntArray = (
            np.column_stack(
                (
                    n1_grid.ravel(),
                    n2_grid.ravel(),
                )
            )
        )

        # The origin does not define a cell boundary and must be removed.
        nonzero = np.any(
            lattice_indices != 0,
            axis=1,
        )

        return lattice_indices[nonzero]

    def construct_halfspaces(self) -> FloatArray:
        """
        Construct the Wigner--Seitz half-plane inequalities.

        Each lattice vector ``R`` defines

        .. math::

            \\mathbf{R}\\cdot\\mathbf{x}
            -
            \frac{|\\mathbf{R}|^2}{2}
            \\leq
            0.

        Returns
        -------
        FloatArray
            Half-plane coefficients with shape
            ``(number_of_halfspaces, 3)``.
        """
        lattice_indices = (
            self.construct_indices()
        )

        lattice_vectors = self.lattice.vector(
            indices=lattice_indices,
        )

        offsets = (
            -0.5
            * np.sum(
                lattice_vectors**2,
                axis=1,
            )
        )

        return np.column_stack(
            (
                lattice_vectors,
                offsets,
            )
        )

    def construct_vertices(self) -> FloatArray:
        """
        Construct the Wigner--Seitz polygon vertices.

        Returns
        -------
        FloatArray
            Counterclockwise polygon vertices with shape
            ``(number_of_vertices, 2)``.
        """
        intersection = HalfspaceIntersection(
            self.halfspaces,
            np.zeros(
                2,
                dtype=np.float64,
            ),
        )

        vertices: FloatArray = np.asarray(
            intersection.intersections,
            dtype=np.float64,
        )

        # HalfspaceIntersection does not guarantee cyclic vertex ordering.
        # Sorting by polar angle produces a counterclockwise polygon.
        angles = np.arctan2(
            vertices[:, 1],
            vertices[:, 0],
        )

        return vertices[
            np.argsort(angles)
        ]

    def contains(
        self,
        point: FloatArray,
    ) -> bool:
        """
        Determine whether a point lies inside the cell.

        Parameters
        ----------
        point:
            Cartesian point with shape ``(2,)``.

        Returns
        -------
        bool
            ``True`` when the point satisfies every defining half-plane.

        Raises
        ------
        ValueError
            If ``point`` does not have shape ``(2,)``.
        """
        point_array: FloatArray = np.asarray(
            point,
            dtype=np.float64,
        )

        if point_array.shape != (2,):
            raise ValueError(
                "point must have shape (2,)."
            )

        residuals = (
            self.halfspaces[:, :2]
            @ point_array
            + self.halfspaces[:, 2]
        )

        return bool(
            np.all(
                residuals <= 1.0e-12
            )
        )


class FirstBrillouinZone2D(
    WignerSeitzCell2D,
    FirstBrillouinZone,
):
    r"""
    First Brillouin zone of a two-dimensional reciprocal lattice.

    The first Brillouin zone is the Wigner--Seitz cell of the reciprocal
    lattice.

    Parameters
    ----------
    reciprocal_lattice:
        Reciprocal lattice whose first Brillouin zone is constructed.
    neighbor_shell:
        Number of reciprocal-lattice index shells used to construct the
        half-plane intersection.
    """

    def __init__(
        self,
        reciprocal_lattice: ReciprocalLattice2D,
        *,
        neighbor_shell: int = 2,
    ) -> None:
        self._reciprocal_lattice = (
            reciprocal_lattice
        )

        # The reciprocal lattice is the source lattice for the Wigner--Seitz
        # construction.
        self._lattice = reciprocal_lattice
        self.neighbor_shell = neighbor_shell

        self.check_args()

        self.halfspaces: FloatArray = (
            self.construct_halfspaces()
        )

        self.vertices: FloatArray = (
            self.construct_vertices()
        )

        self._convex_hull = ConvexHull(
            self.vertices
        )

        self.halfspaces.setflags(write=False)
        self.vertices.setflags(write=False)

    def check_args(self) -> None:
        """
        Validate the first-Brillouin-zone arguments.

        Returns
        -------
        None

        Raises
        ------
        TypeError
            If ``reciprocal_lattice`` is not a
            ``ReciprocalLattice2D`` instance or ``neighbor_shell`` is not an
            integer.
        ValueError
            If ``neighbor_shell`` is less than one.
        """
        if not isinstance(
            self._reciprocal_lattice,
            ReciprocalLattice2D,
        ):
            raise TypeError(
                "reciprocal_lattice must be a "
                "ReciprocalLattice2D instance."
            )

        if not isinstance(
            self.neighbor_shell,
            (int, np.integer),
        ):
            raise TypeError(
                "neighbor_shell must be an integer."
            )

        if self.neighbor_shell < 1:
            raise ValueError(
                "neighbor_shell must be at least 1."
            )

    @property
    def reciprocal_lattice(
        self,
    ) -> ReciprocalLattice2D:
        """
        Return the reciprocal lattice.

        Returns
        -------
        ReciprocalLattice2D
            Reciprocal lattice that generates the zone.
        """
        return self._reciprocal_lattice

    @property
    def lattice(
        self,
    ) -> ReciprocalLattice2D:
        """
        Return the source lattice of the Wigner--Seitz construction.

        Returns
        -------
        ReciprocalLattice2D
            Reciprocal lattice viewed as the source lattice.
        """
        return self._reciprocal_lattice

    def reduce(
        self,
        wavevector: FloatArray,
    ) -> FloatArray:
        """
        Reduce a wavevector into the first Brillouin zone.

        The method subtracts the nearest reciprocal-lattice vector:

        .. math::

            \\mathbf{k}_{\\mathrm{BZ}}
            =
            \\mathbf{k}
            -
            \\mathbf{G}_{\\mathrm{nearest}}.

        Parameters
        ----------
        wavevector:
            Cartesian wavevector with shape ``(2,)``.

        Returns
        -------
        FloatArray
            Equivalent wavevector inside the first Brillouin zone.

        Raises
        ------
        ValueError
            If ``wavevector`` does not have shape ``(2,)``.
        """
        wavevector_array: FloatArray = np.asarray(
            wavevector,
            dtype=np.float64,
        )

        if wavevector_array.shape != (2,):
            raise ValueError(
                "wavevector must have shape (2,)."
            )

        # Estimate the nearest reciprocal index using fractional reciprocal
        # coordinates.
        fractional_indices = np.linalg.solve(
            self.reciprocal_lattice.primitive_basis,
            wavevector_array,
        )

        central_indices = np.rint(
            fractional_indices
        ).astype(np.int64)

        # For a nonorthogonal reciprocal basis, componentwise rounding does not
        # always identify the nearest reciprocal point. Search nearby indices
        # around the rounded estimate.
        offset_values = np.arange(
            -2,
            3,
            dtype=np.int64,
        )

        offset1_grid, offset2_grid = np.meshgrid(
            offset_values,
            offset_values,
            indexing="ij",
        )

        index_offsets: IntArray = np.column_stack(
            (
                offset1_grid.ravel(),
                offset2_grid.ravel(),
            )
        )

        candidate_indices = (
            central_indices[None, :]
            + index_offsets
        )

        candidate_reciprocal_vectors = (
            self.reciprocal_lattice.vector(
                indices=candidate_indices,
            )
        )

        reduced_candidates = (
            wavevector_array[None, :]
            - candidate_reciprocal_vectors
        )

        candidate_norms_squared = np.sum(
            reduced_candidates**2,
            axis=1,
        )

        nearest_index = np.argmin(
            candidate_norms_squared
        )

        return reduced_candidates[
            nearest_index
        ]
