import numpy as np
from abc import ABC, abstractmethod

import numpy as np
from abc import ABC


class Lattice(ABC):
    """
    Base class for a Bravais lattice.

    A Bravais lattice is generated by primitive vectors

        a_1, a_2, ..., a_d

    collected as columns of the matrix A,

        A = [a_1 a_2 ... a_d].

    A lattice point is

        R = A n,

    where n is an integer-valued coordinate vector.
    """

    def __init__(self, vectors: list[np.ndarray]):
        tol = 1.0e-14

        self.vectors: list[np.ndarray] = [
            self.as_vector(v) for v in vectors
        ]

        self.dim: int = len(self.vectors)

        for v in self.vectors:
            if v.shape != (self.dim,):
                raise ValueError(
                    f"Expected vector shape {(self.dim,)}, got {v.shape}"
                )

        self.A: np.ndarray = np.column_stack(self.vectors)

        if abs(np.linalg.det(self.A)) < tol:
            raise ValueError("Lattice vectors are linearly dependent.")

    @staticmethod
    def as_vector(v: np.ndarray) -> np.ndarray:
        return np.asarray(v, dtype=float).copy()

    def length(self, i: int) -> float:
        """
        Return the length of primitive vector a_i.

        Uses zero-based indexing:
            i = 0 gives |a_1|
            i = 1 gives |a_2|
            i = 2 gives |a_3|
        """
        return np.linalg.norm(self.vectors[i])

    @property
    def omega(self) -> float:
        """
        Unit cell measure.

        In 1D: length
        In 2D: area
        In 3D: volume
        """
        return abs(np.linalg.det(self.A))

    @property
    def lengths(self) -> np.ndarray:
        return np.array([
            np.linalg.norm(v) for v in self.vectors
        ])

    def get_R(self, n: np.ndarray) -> np.ndarray:
        """
        Return the lattice vector R = A n.
        """
        n = np.asarray(n, dtype=int)

        if n.shape != (self.dim,):
            raise ValueError(
                f"Expected index shape {(self.dim,)}, got {n.shape}"
            )

        return self.A @ n

class Lattice1D(Lattice):
    def __init__(self, a: float = 1.0):
        a1 = np.array([a], dtype=float)
        super().__init__([a1])

    @property
    def a1(self) -> np.ndarray:
        return self.vectors[0]

    @property
    def a1_length(self) -> float:
        return self.length(0)
    
    
class Lattice2D(Lattice):
    def __init__(
        self,
        a1: np.ndarray | None = None,
        a2: np.ndarray | None = None,
    ):
        if a1 is None:
            a1 = np.array([1.0, 0.0])
        if a2 is None:
            a2 = np.array([0.0, 1.0])

        super().__init__([a1, a2])

    @property
    def a1(self) -> np.ndarray:
        return self.vectors[0]

    @property
    def a2(self) -> np.ndarray:
        return self.vectors[1]

    @property
    def a1_length(self) -> float:
        return self.length(0)

    @property
    def a2_length(self) -> float:
        return self.length(1)

    @property
    def area(self) -> float:
        return self.omega
    
class Lattice3D(Lattice):
    def __init__(
        self,
        a1: np.ndarray | None = None,
        a2: np.ndarray | None = None,
        a3: np.ndarray | None = None,
    ):
        if a1 is None:
            a1 = np.array([1.0, 0.0, 0.0])
        if a2 is None:
            a2 = np.array([0.0, 1.0, 0.0])
        if a3 is None:
            a3 = np.array([0.0, 0.0, 1.0])

        super().__init__([a1, a2, a3])

    @property
    def a1(self) -> np.ndarray:
        return self.vectors[0]

    @property
    def a2(self) -> np.ndarray:
        return self.vectors[1]

    @property
    def a3(self) -> np.ndarray:
        return self.vectors[2]

    @property
    def a1_length(self) -> float:
        return self.length(0)

    @property
    def a2_length(self) -> float:
        return self.length(1)

    @property
    def a3_length(self) -> float:
        return self.length(2)
    
    @property
    def volume(self) -> float:
        return self.omega